package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// schema is the parsed components.beach.yaml.
type schema struct {
	Package    string
	Components []component
}

// component is one ECS component type: a named flat struct of typed fields.
type component struct {
	Name   string
	Doc    string
	Fields []field
}

type field struct {
	Name string
	Type string
}

// cmdECS implements `beach ecs <sub>`. The only subcommand is `gen`.
func cmdECS(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("ecs: expected a subcommand (gen)")
	}
	switch args[0] {
	case "gen":
		return cmdECSGen(args[1:])
	default:
		return fmt.Errorf("ecs: unknown subcommand %q (want: gen)", args[0])
	}
}

// cmdECSGen reads components.beach.yaml and writes Go structs plus an
// ecs.Register call per component. The ecs engine is purely generic (no schema
// codegen entrypoint of its own), so this generator targets ecs's public
// Register[T] API directly: the generated structs are ready for ecs.Add/Get and
// register with a stable schema id of "<package>.<Name>".
func cmdECSGen(args []string) error {
	fs := flag.NewFlagSet("ecs gen", flag.ContinueOnError)
	file := fs.String("file", "components.beach.yaml", "component schema file")
	out := fs.String("out", "", "output Go file (default: components_gen.go beside the schema)")
	pkg := fs.String("pkg", "", "package name override (default: schema's package: field)")
	if err := fs.Parse(args); err != nil {
		return err
	}

	src, err := os.ReadFile(*file)
	if err != nil {
		return fmt.Errorf("ecs gen: read %s: %w", *file, err)
	}
	sc, err := parseSchema(src)
	if err != nil {
		return fmt.Errorf("ecs gen: %s: %w", *file, err)
	}
	if *pkg != "" {
		sc.Package = *pkg
	}
	if sc.Package == "" {
		return fmt.Errorf("ecs gen: no package: in %s and no --pkg given", *file)
	}
	if len(sc.Components) == 0 {
		return fmt.Errorf("ecs gen: no components declared in %s", *file)
	}

	code, err := renderComponents(sc)
	if err != nil {
		return err
	}

	dst := *out
	if dst == "" {
		dst = filepath.Join(filepath.Dir(*file), "components_gen.go")
	}
	if err := os.WriteFile(dst, code, 0o644); err != nil {
		return fmt.Errorf("ecs gen: write %s: %w", dst, err)
	}
	fmt.Printf("wrote %s (%d components)\n", dst, len(sc.Components))
	return nil
}

// componentsTmpl is the codegen template. It emits one struct per component and
// a single init() that registers each with ecs using a stable schema id.
var componentsTmpl = template.Must(template.New("components").Parse(
	`// Code generated by "beach ecs gen"; DO NOT EDIT.

package {{.Package}}

import ecs "github.com/ThirdCoastInteractive/Beach/pkg/ecs"

{{range .Components}}
{{if .Doc}}// {{.Name}} {{.Doc}}{{else}}// {{.Name}} is a generated ECS component.{{end}}
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}}
{{- end}}
}
{{end}}
// init registers every generated component with ecs under a stable schema id so
// snapshots survive type renames and field reordering.
func init() {
{{- range .Components}}
	ecs.Register[{{.Name}}]("{{$.Package}}.{{.Name}}")
{{- end}}
}
`))

// renderComponents executes the template and gofmts the result.
func renderComponents(sc schema) ([]byte, error) {
	var buf bytes.Buffer
	if err := componentsTmpl.Execute(&buf, sc); err != nil {
		return nil, fmt.Errorf("ecs gen: render: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("ecs gen: gofmt generated code: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

// parseSchema parses the small, fixed components.beach.yaml grammar with a
// hand-written line scanner. The grammar is intentionally narrow:
//
//	package: components
//	components:
//	  - name: Position
//	    doc: A board position.
//	    fields:
//	      - { name: X, type: int }
//	      - { name: Y, type: int }
//
// Keeping it stdlib-only (no yaml dependency) is a deliberate constraint; the
// schema shape is fixed, so a full YAML engine is not warranted.
func parseSchema(src []byte) (schema, error) {
	var sc schema
	var cur *component
	// componentIndent is the indent of the current component's "- name:" line.
	// A "- name:" at strictly greater indent is a block-style field, not a new
	// component — indentation is the only thing that tells them apart.
	componentIndent := -1

	lines := strings.Split(strings.ReplaceAll(string(src), "\r\n", "\n"), "\n")
	for n, raw := range lines {
		line := stripComment(raw)
		if strings.TrimSpace(line) == "" {
			continue
		}
		indent := indentOf(line)
		trimmed := strings.TrimSpace(line)

		isComponentStart := strings.HasPrefix(trimmed, "- name:") &&
			(componentIndent == -1 || indent <= componentIndent)
		isBlockFieldStart := strings.HasPrefix(trimmed, "- name:") && !isComponentStart

		switch {
		case indent == 0 && strings.HasPrefix(trimmed, "package:"):
			sc.Package = identName(strings.TrimSpace(strings.TrimPrefix(trimmed, "package:")))

		case indent == 0 && strings.HasPrefix(trimmed, "components:"):
			// header; entries follow

		case isComponentStart:
			sc.Components = append(sc.Components, component{
				Name: identName(strings.TrimSpace(strings.TrimPrefix(trimmed, "- name:"))),
			})
			cur = &sc.Components[len(sc.Components)-1]
			componentIndent = indent

		case isBlockFieldStart:
			if cur == nil {
				return sc, fmt.Errorf("line %d: field before any component", n+1)
			}
			cur.Fields = append(cur.Fields, field{Name: identName(strings.TrimSpace(strings.TrimPrefix(trimmed, "- name:")))})

		case strings.HasPrefix(trimmed, "doc:"):
			if cur == nil {
				return sc, fmt.Errorf("line %d: doc: before any component", n+1)
			}
			cur.Doc = strings.Trim(strings.TrimSpace(strings.TrimPrefix(trimmed, "doc:")), `"'`)

		case trimmed == "fields:":
			// fields header; entries follow

		case strings.HasPrefix(trimmed, "- {") || strings.HasPrefix(trimmed, "-{"):
			if cur == nil {
				return sc, fmt.Errorf("line %d: field before any component", n+1)
			}
			f, err := parseFlowField(trimmed)
			if err != nil {
				return sc, fmt.Errorf("line %d: %w", n+1, err)
			}
			cur.Fields = append(cur.Fields, f)

		case strings.HasPrefix(trimmed, "name:"):
			// block-style field continuation: a bare "name:" with no leading dash.
			if cur == nil {
				return sc, fmt.Errorf("line %d: name: before any component", n+1)
			}
			cur.Fields = append(cur.Fields, field{Name: identName(strings.TrimSpace(strings.TrimPrefix(trimmed, "name:")))})

		case strings.HasPrefix(trimmed, "type:"):
			if cur == nil || len(cur.Fields) == 0 {
				return sc, fmt.Errorf("line %d: type: with no field", n+1)
			}
			cur.Fields[len(cur.Fields)-1].Type = goType(strings.TrimSpace(strings.TrimPrefix(trimmed, "type:")))

		default:
			return sc, fmt.Errorf("line %d: unrecognized line %q", n+1, trimmed)
		}
	}

	return sc, validateSchema(sc)
}

// parseFlowField parses "- { name: X, type: int }".
func parseFlowField(s string) (field, error) {
	s = strings.TrimPrefix(s, "-")
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "{")
	s = strings.TrimSuffix(s, "}")
	var f field
	for _, pair := range strings.Split(s, ",") {
		kv := strings.SplitN(pair, ":", 2)
		if len(kv) != 2 {
			continue
		}
		key := strings.TrimSpace(kv[0])
		val := strings.TrimSpace(kv[1])
		switch key {
		case "name":
			f.Name = identName(val)
		case "type":
			f.Type = goType(val)
		}
	}
	if f.Name == "" {
		return f, fmt.Errorf("field missing name in %q", s)
	}
	if f.Type == "" {
		return f, fmt.Errorf("field %q missing type", f.Name)
	}
	return f, nil
}

// validateSchema checks names are exported-capable Go identifiers and types are
// in the supported snapshot-friendly set.
func validateSchema(sc schema) error {
	allowed := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true, "bool": true, "string": true, "byte": true, "rune": true,
	}
	seen := map[string]bool{}
	for _, c := range sc.Components {
		if !isGoIdent(c.Name) {
			return fmt.Errorf("component name %q is not a valid Go identifier", c.Name)
		}
		if seen[c.Name] {
			return fmt.Errorf("duplicate component %q", c.Name)
		}
		seen[c.Name] = true
		for _, f := range c.Fields {
			if !isGoIdent(f.Name) {
				return fmt.Errorf("component %q field name %q is not a valid Go identifier", c.Name, f.Name)
			}
			if !allowed[f.Type] {
				return fmt.Errorf("component %q field %q has unsupported type %q (use a scalar Go type)", c.Name, f.Name, f.Type)
			}
		}
	}
	return nil
}

// --- small string helpers ---

func stripComment(line string) string {
	// Strip a "#"-comment that is not inside braces/quotes. The schema has no
	// "#" in values, so a naive split is safe.
	if i := strings.IndexByte(line, '#'); i >= 0 {
		return line[:i]
	}
	return line
}

func indentOf(line string) int {
	return len(line) - len(strings.TrimLeft(line, " \t"))
}

func identName(s string) string {
	return strings.Trim(strings.TrimSpace(s), `"'`)
}

// goType normalizes a declared type token.
func goType(s string) string {
	return strings.Trim(strings.TrimSpace(s), `"'`)
}

func isGoIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') {
			continue
		}
		if i > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}
