package theme

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ThirdCoastInteractive/Beach/pkg/color"
)

// Emission.
//
// The stylesheet keeps every *rule*; this emits only the ~40 *values* the rules
// reference. That split is what the token indirection was always for, and it is
// what makes a theme swappable at runtime: app.css is a build artefact, and the
// block below is a string a request can produce.
//
// Values go out as oklch() rather than hex. A hex literal is six opaque digits;
// oklch(0.72 0.15 205) says lightness, vividness and hue, which is the same
// information the theme was specified in. Browser support has been Baseline
// since 2023.

// tokenOrder is the order tokens are emitted in — grouped the way the ladder is
// read rather than alphabetically, so a human diffing two themes can see which
// part moved.
var tokenOrder = []string{
	"--color-paper", "--color-panel", "--color-panel-hover",
	"--color-fg-strong", "--color-fg-default", "--color-fg-muted", "--color-fg-disabled",
	"--color-line-soft", "--color-line-strong",
	"--color-accent", "--color-accent-hover", "--color-accent-text",
	"--color-accent-soft", "--color-on-accent",
	"--color-accent-2", "--color-accent-3",
	"--color-good", "--color-warn", "--color-bad", "--color-info",
}

// colors returns the scheme's named tokens, less the series ramp.
func (s Scheme) colors() map[string]color.OKLCH {
	return map[string]color.OKLCH{
		"--color-paper":        s.Paper,
		"--color-panel":        s.Panel,
		"--color-panel-hover":  s.PanelHover,
		"--color-fg-strong":    s.FgStrong,
		"--color-fg-default":   s.FgDefault,
		"--color-fg-muted":     s.FgMuted,
		"--color-fg-disabled":  s.FgDisabled,
		"--color-line-soft":    s.LineSoft,
		"--color-line-strong":  s.LineStrong,
		"--color-accent":       s.Accent,
		"--color-accent-hover": s.AccentHover,
		"--color-accent-text":  s.AccentText,
		"--color-accent-soft":  s.AccentSoft,
		"--color-on-accent":    s.OnAccent,
		"--color-accent-2":     s.Accent2,
		"--color-accent-3":     s.Accent3,
		"--color-good":         s.Good,
		"--color-warn":         s.Warn,
		"--color-bad":          s.Bad,
		"--color-info":         s.Info,
	}
}

// Tokens returns every token in the scheme as CSS custom-property name → value.
func (s Scheme) Tokens() map[string]string {
	out := make(map[string]string, len(tokenOrder)+SeriesCount)
	for name, c := range s.colors() {
		out[name] = c.CSS()
	}
	for i, c := range s.Series {
		out[seriesName(i)] = c.CSS()
	}
	return out
}

// Hexes returns the same tokens as hex. Nothing paints from these — they exist
// because a contrast checker, a screenshot diff and a person reading a test
// failure all speak hex.
func (s Scheme) Hexes() map[string]string {
	out := make(map[string]string, len(tokenOrder)+SeriesCount)
	for name, c := range s.colors() {
		out[name] = c.Hex()
	}
	for i, c := range s.Series {
		out[seriesName(i)] = c.Hex()
	}
	return out
}

// TokenNames lists every token a scheme defines, in emission order. It is the
// contract both schemes are held to: a token present in one and missing from the
// other would inherit across the boundary and paint the wrong colour.
func TokenNames() []string {
	out := append([]string(nil), tokenOrder...)
	for i := range SeriesCount {
		out = append(out, seriesName(i))
	}
	return out
}

func seriesName(i int) string { return fmt.Sprintf("--color-series-%c", 'a'+i) }

// CSS renders the theme as the three-state block the framework serves.
//
// The three states are a real thing, not defensiveness. A visitor is in exactly
// one of them: they have chosen light, they have chosen dark, or they have
// chosen nothing and the operating system speaks for them. Only the last is a
// media query, and it must not override an explicit choice — hence the :not()
// guard, without which the toggle works in one direction and silently fails in
// the other.
//
// Dark sits on bare :root, so the kit stays dark-first and stays correct where
// the media query is unsupported. The query is what makes it automatic.
func (t Theme) CSS() string {
	var b strings.Builder

	b.WriteString("/* " + t.Preset.Title + " — generated by pkg/theme from a dozen parameters;\n")
	b.WriteString("   every stop is solved against the contrast it owes, so these values are an\n")
	b.WriteString("   output, not a decision. Change the preset, not the numbers. */\n")

	b.WriteString(":root {\n")
	writeScheme(&b, t.Dark, "  ")
	b.WriteString("}\n\n")

	b.WriteString("/* No explicit choice: the operating system speaks. The :not() guard is what\n")
	b.WriteString("   keeps an explicit dark choice from being overridden by a light OS. */\n")
	b.WriteString("@media (prefers-color-scheme: light) {\n  :root:not([data-theme=\"dark\"]) {\n")
	writeScheme(&b, t.Light, "    ")
	b.WriteString("  }\n}\n\n")

	b.WriteString("/* An explicit choice, stamped on <html> by the page shell from the visitor's\n")
	b.WriteString("   preference cookie — server-rendered, so there is no flash of the wrong\n")
	b.WriteString("   theme and no script in the head. */\n")
	b.WriteString(":root[data-theme=\"light\"] {\n")
	writeScheme(&b, t.Light, "  ")
	b.WriteString("}\n\n:root[data-theme=\"dark\"] {\n")
	writeScheme(&b, t.Dark, "  ")
	b.WriteString("}\n")

	return b.String()
}

func writeScheme(b *strings.Builder, s Scheme, indent string) {
	tok := s.Tokens()
	for _, name := range tokenOrder {
		fmt.Fprintf(b, "%s%s: %s;\n", indent, name, tok[name])
	}
	for i := range SeriesCount {
		n := seriesName(i)
		fmt.Fprintf(b, "%s%s: %s;\n", indent, n, tok[n])
	}
}

// Pairs is every contrast obligation the kit actually paints, as measured facts.
//
// It is exported because two different things need the same list and must not
// keep their own copies: the test that fails the build when a pair drops below
// its threshold, and the specimen page that shows the ratios to a reader. A
// second copy is a copy that drifts, and it would report ratios for colours the
// page is no longer painting.
func (s Scheme) Pairs() []Pair {
	return []Pair{
		{"body text on the page", s.FgDefault, s.Paper, color.AAText, "1.4.3"},
		{"body text on a card", s.FgDefault, s.Panel, color.AAText, "1.4.3"},
		{"headings on a card", s.FgStrong, s.Panel, color.AAText, "1.4.3"},
		{"muted text on the page", s.FgMuted, s.Paper, color.AAText, "1.4.3"},
		{"muted text on a card", s.FgMuted, s.Panel, color.AAText, "1.4.3"},
		{"muted text on a raised panel", s.FgMuted, s.PanelHover, color.AAText, "1.4.3"},

		{"accent button label", s.OnAccent, s.Accent, color.AAText, "1.4.3"},
		{"accent button label, hovered", s.OnAccent, s.AccentHover, color.AAText, "1.4.3"},

		{"link text on the page", s.AccentText, s.Paper, color.AAText, "1.4.3"},
		{"link text on a card", s.AccentText, s.Panel, color.AAText, "1.4.3"},
		{"ghost button label, hovered", s.AccentText, s.AccentSoft, color.AAText, "1.4.3"},

		{"success text", s.Good, s.Panel, color.AAText, "1.4.3"},
		{"warning text", s.Warn, s.Panel, color.AAText, "1.4.3"},
		{"error text", s.Bad, s.Panel, color.AAText, "1.4.3"},
		{"info text", s.Info, s.Panel, color.AAText, "1.4.3"},
		{"field error text", s.Bad, s.Paper, color.AAText, "1.4.3"},
		{"category B as text", s.Accent2, s.Panel, color.AAText, "1.4.3"},
		{"category C as text", s.Accent3, s.Panel, color.AAText, "1.4.3"},

		// The role buttons put paper ink on the role fill. The old palette had
		// no check for this pair at all, because neither colour was chosen with
		// the other in mind.
		{"success button label", s.Paper, s.Good, color.AAText, "1.4.3"},
		{"warning button label", s.Paper, s.Warn, color.AAText, "1.4.3"},
		{"error button label", s.Paper, s.Bad, color.AAText, "1.4.3"},
		{"info button label", s.Paper, s.Info, color.AAText, "1.4.3"},

		{"focus ring on the page", s.Accent, s.Paper, color.AANonText, "1.4.11"},
		{"focus ring on a card", s.Accent, s.Panel, color.AANonText, "1.4.11"},
		{"focus ring on a raised panel", s.Accent, s.PanelHover, color.AANonText, "1.4.11"},
		{"input edge on the page", s.LineStrong, s.Paper, color.AANonText, "1.4.11"},
		{"input edge on a card", s.LineStrong, s.Panel, color.AANonText, "1.4.11"},
		{"input edge on a raised panel", s.LineStrong, s.PanelHover, color.AANonText, "1.4.11"},
		{"disabled text on a card", s.FgDisabled, s.Panel, color.AANonText, "1.4.3"},
	}
}

// Pair is one contrast obligation, with the criterion that imposes it.
type Pair struct {
	What      string
	Fg, Bg    color.OKLCH
	Min       float64
	Criterion string
}

// Ratio is the measured contrast of the pair.
func (p Pair) Ratio() float64 { return color.Contrast(p.Fg, p.Bg) }

// Passes reports whether the pair meets its threshold.
func (p Pair) Passes() bool { return p.Ratio() >= p.Min }

// SeriesPairs holds each chart series against the page. A series colour is the
// whole encoding of a line or a wedge, so one that sinks into the background
// takes its data with it.
func (s Scheme) SeriesPairs() []Pair {
	out := make([]Pair, 0, SeriesCount)
	for i, c := range s.Series {
		out = append(out, Pair{
			What:      "chart series " + string(rune('a'+i)),
			Fg:        c,
			Bg:        s.Paper,
			Min:       color.AANonText,
			Criterion: "1.4.11",
		})
	}
	return out
}

// sortedNames is a stable name list for diffing two token maps.
func sortedNames(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// Diff reports token values present in a but different in b, as "name: a → b"
// lines. It backs the test that re-derives the palette and compares it with what
// the stylesheet actually says.
func Diff(a, b map[string]string) []string {
	var out []string
	for _, name := range sortedNames(a) {
		if got, ok := b[name]; !ok {
			out = append(out, name+": missing")
		} else if got != a[name] {
			out = append(out, fmt.Sprintf("%s: %s → %s", name, a[name], got))
		}
	}
	return out
}
