// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"sort"
	"sync"
)

// The icon API is ui.Icon(name, opts...). It renders an icon-font glyph and,
// as a side effect of rendering, records the glyph name so a build-time pass
// can subset the shipped font to exactly the glyphs the code references — the
// font contains only what ui.Icon actually names.
//
// Rendering is markup-and-CSS only: an <i> with a class the stylesheet maps to
// a font glyph, plus tokenized options (spin animation, size). No script.

// Size is the icon size step. It mirrors the component-level size vocabulary
// without importing the component package.
type Size string

const (
	SizeSm Size = "sm"
	SizeMd Size = ""
	SizeLg Size = "lg"
)

// IconOpt configures a single icon. Options are applied to an iconConfig.
type IconOpt func(*iconConfig)

type iconConfig struct {
	spin bool
	size Size
	// label sets an accessible name; empty renders the icon aria-hidden.
	label string
}

// Spin animates the icon with the animation tokens (e.g. a loading gear). It
// is a presentational state, so it stays pure CSS.
func Spin(c *iconConfig) { c.spin = true }

// IconSize sets the icon's size step.
func IconSize(s Size) IconOpt { return func(c *iconConfig) { c.size = s } }

// IconLabel gives the icon an accessible name. Without it the icon renders
// aria-hidden (decorative), which is correct when adjacent text already labels
// it (e.g. inside a Button).
func IconLabel(label string) IconOpt { return func(c *iconConfig) { c.label = label } }

var (
	iconMu   sync.Mutex
	iconUsed = map[string]struct{}{}
)

// recordIcon notes that name is referenced so the subsetter keeps its glyph.
func recordIcon(name string) {
	iconMu.Lock()
	iconUsed[name] = struct{}{}
	iconMu.Unlock()
}

// UsedIcons returns the sorted set of icon names referenced by ui.Icon so far.
// The build-time font-subsetting pass reads this to ship only the needed glyphs.
func UsedIcons() []string {
	iconMu.Lock()
	out := make([]string, 0, len(iconUsed))
	for n := range iconUsed {
		out = append(out, n)
	}
	iconMu.Unlock()
	sort.Strings(out)
	return out
}

// iconClass resolves the option set into the final class list and accessible
// label, recording the glyph for the font subsetter. Color, size, and the spin
// animation come from design tokens via the icon classes; nothing is hardcoded.
func iconClass(name string, opts []IconOpt) (class, label string) {
	recordIcon(name)
	cfg := iconConfig{}
	for _, o := range opts {
		o(&cfg)
	}
	class = "icon icon-" + name
	if cfg.spin {
		class += " icon-spin"
	}
	if cfg.size != "" {
		class += " icon-" + string(cfg.size)
	}
	return class, cfg.label
}

// Icon renders an icon glyph by name with optional modifiers, e.g.
//
//	@ui.Icon("gear", ui.Spin)
func Icon(name string, opts ...IconOpt) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		class, label := iconClass(name, opts)
		if label != "" {
			var templ_7745c5c3_Var2 = []any{class}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<i class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/icon.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" role=\"img\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/icon.templ`, Line: 98, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></i>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			var templ_7745c5c3_Var5 = []any{class}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<i class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var5).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/icon.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" aria-hidden=\"true\"></i>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
