-- +goose Up
-- NOTE: idempotent DDL (IF NOT EXISTS). pg.Migrate keys each source's goose
-- version table off its FIRST migration filename, so adding a migration does not
-- orphan the recorded history. Idempotency is the belt-and-suspenders: if a
-- version table is ever missing (e.g. a source first applied with several
-- migrations at once, then extended), goose re-runs from 00001 and this stays a
-- harmless no-op instead of failing on "relation already exists".
-- +goose StatementBegin
-- id is GENERATED BY DEFAULT (not ALWAYS): an insert that omits id gets a
-- DB-minted value (the example-app login path), while an app that mints its own
-- 64-bit identifier may supply id explicitly. Both are first-class.
CREATE TABLE IF NOT EXISTS users (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   text        NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);
-- +goose StatementEnd

-- Local username/password credentials. password_hash is an argon2id PHC string;
-- it is a secret column and must never appear in a RETURNING clause or SELECT *.
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_credentials_local (
    user_id            bigint      PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    password_hash      text        NOT NULL,
    failed_login_count integer     NOT NULL DEFAULT 0,
    locked_until       timestamptz,
    updated_at         timestamptz NOT NULL DEFAULT now()
);
-- +goose StatementEnd

-- --- RBAC: three tables, flat "resource:action" permissions ---

-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS roles (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text   NOT NULL UNIQUE
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id    bigint NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission text   NOT NULL,                 -- "resource:action"
    PRIMARY KEY (role_id, permission)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_roles (
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS user_roles_role_id_idx ON user_roles (role_id);
-- +goose StatementEnd

-- --- password reset: hashed single-use tokens, expiry, audit ---
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token_hash bytea       PRIMARY KEY,          -- SHA256(token); raw token never stored
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    used_at    timestamptz
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS password_reset_tokens_user_id_idx ON password_reset_tokens (user_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE password_reset_tokens;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE user_roles;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE role_permissions;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE roles;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE user_credentials_local;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE users;
-- +goose StatementEnd
